server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
            - SetRequestHeader=X-Auth-Token, $http_x_auth_token  # Auth Service'den gelen header'ı User Service'e iletmek
        - id: bill-payment
          uri: http://localhost:8085
          predicates:
            - Path=/bill-payment-service/**
        - id: mail-sender
          uri: http://localhost:8083
          predicates:
            - Path=/mail-sender/**
        - id: eureka
          uri: http://localhost:8084
          predicates:
            - Path=/eureka/**

  main:
    web-application-type: reactive
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

invoice.app.secret: invoice
invoice.app.expires.in: 120000
refresh.token.expires.in: 604800
jwt:
  secret: secretkey