server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
              - Path=/auth-service/**
        - id: invoice
          uri: http://localhost:8082
          predicates:
            - Path=/invoice/**
        - id: mail-sender
          uri: http://localhost:8082
          predicates:
            - Path=/mail-sender/**

  main:
    web-application-type: reactive